// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dleague/v1/envelope.proto (package dleague.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dleague/v1/envelope.proto.
 */
export const file_dleague_v1_envelope: GenFile = /*@__PURE__*/
  fileDesc("ChlkbGVhZ3VlL3YxL2VudmVsb3BlLnByb3RvEgpkbGVhZ3VlLnYxIlYKCEVudmVsb3BlEiUKBHR5cGUYASABKA4yFy5kbGVhZ3VlLnYxLk1lc3NhZ2VUeXBlEhIKCnJlcXVlc3RfaWQYAiABKAkSDwoHcGF5bG9hZBgDIAEoDCIeCgRQaW5nEhYKDmNsaWVudF91bml4X21zGAEgASgDIjYKBFBvbmcSFgoOY2xpZW50X3VuaXhfbXMYASABKAMSFgoOc2VydmVyX3VuaXhfbXMYAiABKAMiJgoFRXJyb3ISDAoEY29kZRgBIAEoBRIPCgdtZXNzYWdlGAIgASgJIh8KC0F1dGhSZWZyZXNoEhAKCGlkX3Rva2VuGAEgASgJIikKDkF1dGhSZWZyZXNoQWNrEhcKD2V4cGlyZXNfYXRfdW5peBgBIAEoAyqNBAoLTWVzc2FnZVR5cGUSHAoYTUVTU0FHRV9UWVBFX1VOU1BFQ0lGSUVEEAASFQoRTUVTU0FHRV9UWVBFX1BJTkcQARIVChFNRVNTQUdFX1RZUEVfUE9ORxACEhYKEk1FU1NBR0VfVFlQRV9FUlJPUhADEh0KGU1FU1NBR0VfVFlQRV9BVVRIX1JFRlJFU0gQBBIhCh1NRVNTQUdFX1RZUEVfQVVUSF9SRUZSRVNIX0FDSxAFEhoKFk1FU1NBR0VfVFlQRV9HQU1FX01PVkUQBhIbChdNRVNTQUdFX1RZUEVfR0FNRV9TVEFURRAHEiEKHU1FU1NBR0VfVFlQRV9DSEFMTEVOR0VfQ1JFQVRFEAgSJQohTUVTU0FHRV9UWVBFX0NIQUxMRU5HRV9DUkVBVEVfQUNLEAkSHwobTUVTU0FHRV9UWVBFX0NIQUxMRU5HRV9KT0lOEAoSIwofTUVTU0FHRV9UWVBFX0NIQUxMRU5HRV9KT0lOX0FDSxALEh8KG01FU1NBR0VfVFlQRV9BVFRFTVBUX1NVQk1JVBAMEiMKH01FU1NBR0VfVFlQRV9BVFRFTVBUX1NVQk1JVF9BQ0sQDRIiCh5NRVNTQUdFX1RZUEVfTEVBREVSQk9BUkRfUVVFUlkQDhIlCiFNRVNTQUdFX1RZUEVfTEVBREVSQk9BUkRfU05BUFNIT1QQD0I8WjpnaXRodWIuY29tL3RpZW5ubTk5L2RsZWFndWUvc2hhcmVkL3BiL2RsZWFndWUvdjE7ZGxlYWd1ZXYxYgZwcm90bzM");

/**
 * Envelope is the wire frame for every WebSocket message.
 * Payload bytes are the marshaled bytes of the inner message identified by `type`.
 *
 * @generated from message dleague.v1.Envelope
 */
export type Envelope = Message<"dleague.v1.Envelope"> & {
  /**
   * @generated from field: dleague.v1.MessageType type = 1;
   */
  type: MessageType;

  /**
   * @generated from field: string request_id = 2;
   */
  requestId: string;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;
};

/**
 * Describes the message dleague.v1.Envelope.
 * Use `create(EnvelopeSchema)` to create a new message.
 */
export const EnvelopeSchema: GenMessage<Envelope> = /*@__PURE__*/
  messageDesc(file_dleague_v1_envelope, 0);

/**
 * @generated from message dleague.v1.Ping
 */
export type Ping = Message<"dleague.v1.Ping"> & {
  /**
   * @generated from field: int64 client_unix_ms = 1;
   */
  clientUnixMs: bigint;
};

/**
 * Describes the message dleague.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_dleague_v1_envelope, 1);

/**
 * @generated from message dleague.v1.Pong
 */
export type Pong = Message<"dleague.v1.Pong"> & {
  /**
   * @generated from field: int64 client_unix_ms = 1;
   */
  clientUnixMs: bigint;

  /**
   * @generated from field: int64 server_unix_ms = 2;
   */
  serverUnixMs: bigint;
};

/**
 * Describes the message dleague.v1.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export const PongSchema: GenMessage<Pong> = /*@__PURE__*/
  messageDesc(file_dleague_v1_envelope, 2);

/**
 * Error carries a structured error response back to the client.
 *
 * @generated from message dleague.v1.Error
 */
export type Error = Message<"dleague.v1.Error"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message dleague.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_dleague_v1_envelope, 3);

/**
 * AuthRefresh is sent by the client ~50 min into a connection to rotate the
 * Firebase ID token before the current one expires (tokens last 1 hour).
 *
 * @generated from message dleague.v1.AuthRefresh
 */
export type AuthRefresh = Message<"dleague.v1.AuthRefresh"> & {
  /**
   * @generated from field: string id_token = 1;
   */
  idToken: string;
};

/**
 * Describes the message dleague.v1.AuthRefresh.
 * Use `create(AuthRefreshSchema)` to create a new message.
 */
export const AuthRefreshSchema: GenMessage<AuthRefresh> = /*@__PURE__*/
  messageDesc(file_dleague_v1_envelope, 4);

/**
 * AuthRefreshAck is the server's confirmation after successfully re-verifying
 * the supplied token. expires_at_unix is the new token's expiry as Unix epoch seconds.
 *
 * @generated from message dleague.v1.AuthRefreshAck
 */
export type AuthRefreshAck = Message<"dleague.v1.AuthRefreshAck"> & {
  /**
   * @generated from field: int64 expires_at_unix = 1;
   */
  expiresAtUnix: bigint;
};

/**
 * Describes the message dleague.v1.AuthRefreshAck.
 * Use `create(AuthRefreshAckSchema)` to create a new message.
 */
export const AuthRefreshAckSchema: GenMessage<AuthRefreshAck> = /*@__PURE__*/
  messageDesc(file_dleague_v1_envelope, 5);

/**
 * MessageType identifies the payload variant inside Envelope.
 *
 * @generated from enum dleague.v1.MessageType
 */
export enum MessageType {
  /**
   * @generated from enum value: MESSAGE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_TYPE_PING = 1;
   */
  PING = 1,

  /**
   * @generated from enum value: MESSAGE_TYPE_PONG = 2;
   */
  PONG = 2,

  /**
   * @generated from enum value: MESSAGE_TYPE_ERROR = 3;
   */
  ERROR = 3,

  /**
   * @generated from enum value: MESSAGE_TYPE_AUTH_REFRESH = 4;
   */
  AUTH_REFRESH = 4,

  /**
   * @generated from enum value: MESSAGE_TYPE_AUTH_REFRESH_ACK = 5;
   */
  AUTH_REFRESH_ACK = 5,

  /**
   * @generated from enum value: MESSAGE_TYPE_GAME_MOVE = 6;
   */
  GAME_MOVE = 6,

  /**
   * @generated from enum value: MESSAGE_TYPE_GAME_STATE = 7;
   */
  GAME_STATE = 7,

  /**
   * Phase 08: async PvP + leaderboard (8–15; 0–7 already used above).
   *
   * @generated from enum value: MESSAGE_TYPE_CHALLENGE_CREATE = 8;
   */
  CHALLENGE_CREATE = 8,

  /**
   * @generated from enum value: MESSAGE_TYPE_CHALLENGE_CREATE_ACK = 9;
   */
  CHALLENGE_CREATE_ACK = 9,

  /**
   * @generated from enum value: MESSAGE_TYPE_CHALLENGE_JOIN = 10;
   */
  CHALLENGE_JOIN = 10,

  /**
   * @generated from enum value: MESSAGE_TYPE_CHALLENGE_JOIN_ACK = 11;
   */
  CHALLENGE_JOIN_ACK = 11,

  /**
   * @generated from enum value: MESSAGE_TYPE_ATTEMPT_SUBMIT = 12;
   */
  ATTEMPT_SUBMIT = 12,

  /**
   * @generated from enum value: MESSAGE_TYPE_ATTEMPT_SUBMIT_ACK = 13;
   */
  ATTEMPT_SUBMIT_ACK = 13,

  /**
   * @generated from enum value: MESSAGE_TYPE_LEADERBOARD_QUERY = 14;
   */
  LEADERBOARD_QUERY = 14,

  /**
   * @generated from enum value: MESSAGE_TYPE_LEADERBOARD_SNAPSHOT = 15;
   */
  LEADERBOARD_SNAPSHOT = 15,
}

/**
 * Describes the enum dleague.v1.MessageType.
 */
export const MessageTypeSchema: GenEnum<MessageType> = /*@__PURE__*/
  enumDesc(file_dleague_v1_envelope, 0);

