// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dleague/v1/match.proto (package dleague.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dleague/v1/match.proto.
 */
export const file_dleague_v1_match: GenFile = /*@__PURE__*/
  fileDesc("ChZkbGVhZ3VlL3YxL21hdGNoLnByb3RvEgpkbGVhZ3VlLnYxIjkKD0NoYWxsZW5nZUNyZWF0ZRIPCgdnYW1lX2lkGAEgASgJEhUKDXNlZWRfb3ZlcnJpZGUYAiABKAMiSQoSQ2hhbGxlbmdlQ3JlYXRlQWNrEhAKCG1hdGNoX2lkGAEgASgJEhMKC3NoYXJlX3Rva2VuGAIgASgJEgwKBHNlZWQYAyABKAMiJAoNQ2hhbGxlbmdlSm9pbhITCgtzaGFyZV90b2tlbhgBIAEoCSJDChBDaGFsbGVuZ2VKb2luQWNrEhAKCG1hdGNoX2lkGAEgASgJEgwKBHNlZWQYAiABKAMSDwoHZ2FtZV9pZBgDIAEoCSJQCg1BdHRlbXB0U3VibWl0EhAKCG1hdGNoX2lkGAEgASgJEg8KB2d1ZXNzZXMYAiADKAkSDwoHdGltZV9tcxgDIAEoBRILCgN3b24YBCABKAgiNgoQQXR0ZW1wdFN1Ym1pdEFjaxISCgp3aW5uZXJfdWlkGAEgASgJEg4KBnN0YXR1cxgCIAEoCSIzChBMZWFkZXJib2FyZFF1ZXJ5Eg8KB2dhbWVfaWQYASABKAkSDgoGcGVyaW9kGAIgASgJImYKEExlYWRlcmJvYXJkRW50cnkSCwoDdWlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIQCghhdHRlbXB0cxgDIAEoBRIPCgd0aW1lX21zGAQgASgFEgwKBHJhbmsYBSABKAUiRQoTTGVhZGVyYm9hcmRTbmFwc2hvdBIuCghyYW5raW5ncxgBIAMoCzIcLmRsZWFndWUudjEuTGVhZGVyYm9hcmRFbnRyeUI8WjpnaXRodWIuY29tL3RpZW5ubTk5L2RsZWFndWUvc2hhcmVkL3BiL2RsZWFndWUvdjE7ZGxlYWd1ZXYxYgZwcm90bzM");

/**
 * ChallengeCreate is sent by a player after finishing a game to create
 * a shareable async PvP challenge.
 *
 * @generated from message dleague.v1.ChallengeCreate
 */
export type ChallengeCreate = Message<"dleague.v1.ChallengeCreate"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * optional; 0 = use today's daily seed
   *
   * @generated from field: int64 seed_override = 2;
   */
  seedOverride: bigint;
};

/**
 * Describes the message dleague.v1.ChallengeCreate.
 * Use `create(ChallengeCreateSchema)` to create a new message.
 */
export const ChallengeCreateSchema: GenMessage<ChallengeCreate> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 0);

/**
 * ChallengeCreateAck is the server's response to ChallengeCreate.
 *
 * @generated from message dleague.v1.ChallengeCreateAck
 */
export type ChallengeCreateAck = Message<"dleague.v1.ChallengeCreateAck"> & {
  /**
   * @generated from field: string match_id = 1;
   */
  matchId: string;

  /**
   * @generated from field: string share_token = 2;
   */
  shareToken: string;

  /**
   * @generated from field: int64 seed = 3;
   */
  seed: bigint;
};

/**
 * Describes the message dleague.v1.ChallengeCreateAck.
 * Use `create(ChallengeCreateAckSchema)` to create a new message.
 */
export const ChallengeCreateAckSchema: GenMessage<ChallengeCreateAck> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 1);

/**
 * ChallengeJoin is sent by a challenger when opening a share link.
 *
 * @generated from message dleague.v1.ChallengeJoin
 */
export type ChallengeJoin = Message<"dleague.v1.ChallengeJoin"> & {
  /**
   * @generated from field: string share_token = 1;
   */
  shareToken: string;
};

/**
 * Describes the message dleague.v1.ChallengeJoin.
 * Use `create(ChallengeJoinSchema)` to create a new message.
 */
export const ChallengeJoinSchema: GenMessage<ChallengeJoin> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 2);

/**
 * ChallengeJoinAck is the server's response to ChallengeJoin.
 * Note: challenger's attempts are intentionally omitted until after the
 * challengee submits their own attempt (anti-cheat).
 *
 * @generated from message dleague.v1.ChallengeJoinAck
 */
export type ChallengeJoinAck = Message<"dleague.v1.ChallengeJoinAck"> & {
  /**
   * @generated from field: string match_id = 1;
   */
  matchId: string;

  /**
   * @generated from field: int64 seed = 2;
   */
  seed: bigint;

  /**
   * @generated from field: string game_id = 3;
   */
  gameId: string;
};

/**
 * Describes the message dleague.v1.ChallengeJoinAck.
 * Use `create(ChallengeJoinAckSchema)` to create a new message.
 */
export const ChallengeJoinAckSchema: GenMessage<ChallengeJoinAck> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 3);

/**
 * AttemptSubmit records a player's completed game result for a match.
 *
 * @generated from message dleague.v1.AttemptSubmit
 */
export type AttemptSubmit = Message<"dleague.v1.AttemptSubmit"> & {
  /**
   * @generated from field: string match_id = 1;
   */
  matchId: string;

  /**
   * @generated from field: repeated string guesses = 2;
   */
  guesses: string[];

  /**
   * @generated from field: int32 time_ms = 3;
   */
  timeMs: number;

  /**
   * @generated from field: bool won = 4;
   */
  won: boolean;
};

/**
 * Describes the message dleague.v1.AttemptSubmit.
 * Use `create(AttemptSubmitSchema)` to create a new message.
 */
export const AttemptSubmitSchema: GenMessage<AttemptSubmit> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 4);

/**
 * AttemptSubmitAck is the server's response after recording an attempt.
 * status is "pending" if the other player hasn't submitted yet, or "completed"
 * if both sides have submitted and a winner has been decided.
 *
 * @generated from message dleague.v1.AttemptSubmitAck
 */
export type AttemptSubmitAck = Message<"dleague.v1.AttemptSubmitAck"> & {
  /**
   * empty when status is "pending"
   *
   * @generated from field: string winner_uid = 1;
   */
  winnerUid: string;

  /**
   * "pending" | "completed"
   *
   * @generated from field: string status = 2;
   */
  status: string;
};

/**
 * Describes the message dleague.v1.AttemptSubmitAck.
 * Use `create(AttemptSubmitAckSchema)` to create a new message.
 */
export const AttemptSubmitAckSchema: GenMessage<AttemptSubmitAck> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 5);

/**
 * LeaderboardQuery requests the current leaderboard snapshot.
 *
 * @generated from message dleague.v1.LeaderboardQuery
 */
export type LeaderboardQuery = Message<"dleague.v1.LeaderboardQuery"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * "daily" | "all"
   *
   * @generated from field: string period = 2;
   */
  period: string;
};

/**
 * Describes the message dleague.v1.LeaderboardQuery.
 * Use `create(LeaderboardQuerySchema)` to create a new message.
 */
export const LeaderboardQuerySchema: GenMessage<LeaderboardQuery> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 6);

/**
 * LeaderboardEntry is one row in a leaderboard snapshot.
 *
 * @generated from message dleague.v1.LeaderboardEntry
 */
export type LeaderboardEntry = Message<"dleague.v1.LeaderboardEntry"> & {
  /**
   * @generated from field: string uid = 1;
   */
  uid: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: int32 attempts = 3;
   */
  attempts: number;

  /**
   * @generated from field: int32 time_ms = 4;
   */
  timeMs: number;

  /**
   * @generated from field: int32 rank = 5;
   */
  rank: number;
};

/**
 * Describes the message dleague.v1.LeaderboardEntry.
 * Use `create(LeaderboardEntrySchema)` to create a new message.
 */
export const LeaderboardEntrySchema: GenMessage<LeaderboardEntry> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 7);

/**
 * LeaderboardSnapshot is the server's response to LeaderboardQuery.
 *
 * @generated from message dleague.v1.LeaderboardSnapshot
 */
export type LeaderboardSnapshot = Message<"dleague.v1.LeaderboardSnapshot"> & {
  /**
   * @generated from field: repeated dleague.v1.LeaderboardEntry rankings = 1;
   */
  rankings: LeaderboardEntry[];
};

/**
 * Describes the message dleague.v1.LeaderboardSnapshot.
 * Use `create(LeaderboardSnapshotSchema)` to create a new message.
 */
export const LeaderboardSnapshotSchema: GenMessage<LeaderboardSnapshot> = /*@__PURE__*/
  messageDesc(file_dleague_v1_match, 8);

