// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file dleague/v1/wordle.proto (package dleague.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dleague/v1/wordle.proto.
 */
export const file_dleague_v1_wordle: GenFile = /*@__PURE__*/
  fileDesc("ChdkbGVhZ3VlL3YxL3dvcmRsZS5wcm90bxIKZGxlYWd1ZS52MSIvCgpXb3JkbGVIaW50EiEKBmNvbG9ycxgBIAMoDjIRLmRsZWFndWUudjEuQ29sb3IiGwoKV29yZGxlTW92ZRINCgVndWVzcxgBIAEoCSKOAQoLV29yZGxlU3RhdGUSDwoHZ3Vlc3NlcxgBIAMoCRIlCgVoaW50cxgCIAMoCzIWLmRsZWFndWUudjEuV29yZGxlSGludBIaChJhdHRlbXB0c19yZW1haW5pbmcYAyABKAUSCwoDd29uGAQgASgIEgwKBGxvc3QYBSABKAgSEAoIc29sdXRpb24YBiABKAkiRAoMV29yZGxlUmVzdWx0EhAKCHNvbHV0aW9uGAEgASgJEgsKA3dvbhgCIAEoCBIVCg1hdHRlbXB0c191c2VkGAMgASgFKlEKBUNvbG9yEhUKEUNPTE9SX1VOU1BFQ0lGSUVEEAASDgoKQ09MT1JfR1JBWRABEhAKDENPTE9SX1lFTExPVxACEg8KC0NPTE9SX0dSRUVOEANCPFo6Z2l0aHViLmNvbS90aWVubm05OS9kbGVhZ3VlL3NoYXJlZC9wYi9kbGVhZ3VlL3YxO2RsZWFndWV2MWIGcHJvdG8z");

/**
 * WordleHint holds the per-letter color result for one guess.
 *
 * @generated from message dleague.v1.WordleHint
 */
export type WordleHint = Message<"dleague.v1.WordleHint"> & {
  /**
   * @generated from field: repeated dleague.v1.Color colors = 1;
   */
  colors: Color[];
};

/**
 * Describes the message dleague.v1.WordleHint.
 * Use `create(WordleHintSchema)` to create a new message.
 */
export const WordleHintSchema: GenMessage<WordleHint> = /*@__PURE__*/
  messageDesc(file_dleague_v1_wordle, 0);

/**
 * WordleMove is sent client→server carrying the player's guess word.
 *
 * @generated from message dleague.v1.WordleMove
 */
export type WordleMove = Message<"dleague.v1.WordleMove"> & {
  /**
   * @generated from field: string guess = 1;
   */
  guess: string;
};

/**
 * Describes the message dleague.v1.WordleMove.
 * Use `create(WordleMoveSchema)` to create a new message.
 */
export const WordleMoveSchema: GenMessage<WordleMove> = /*@__PURE__*/
  messageDesc(file_dleague_v1_wordle, 1);

/**
 * WordleState is sent server→client after each move.
 * solution is only populated when the game is terminal (won or lost).
 *
 * @generated from message dleague.v1.WordleState
 */
export type WordleState = Message<"dleague.v1.WordleState"> & {
  /**
   * @generated from field: repeated string guesses = 1;
   */
  guesses: string[];

  /**
   * @generated from field: repeated dleague.v1.WordleHint hints = 2;
   */
  hints: WordleHint[];

  /**
   * @generated from field: int32 attempts_remaining = 3;
   */
  attemptsRemaining: number;

  /**
   * @generated from field: bool won = 4;
   */
  won: boolean;

  /**
   * @generated from field: bool lost = 5;
   */
  lost: boolean;

  /**
   * solution is intentionally omitted until terminal to prevent cheating.
   *
   * @generated from field: string solution = 6;
   */
  solution: string;
};

/**
 * Describes the message dleague.v1.WordleState.
 * Use `create(WordleStateSchema)` to create a new message.
 */
export const WordleStateSchema: GenMessage<WordleState> = /*@__PURE__*/
  messageDesc(file_dleague_v1_wordle, 2);

/**
 * WordleResult summarises a completed game for leaderboard / history.
 *
 * @generated from message dleague.v1.WordleResult
 */
export type WordleResult = Message<"dleague.v1.WordleResult"> & {
  /**
   * @generated from field: string solution = 1;
   */
  solution: string;

  /**
   * @generated from field: bool won = 2;
   */
  won: boolean;

  /**
   * @generated from field: int32 attempts_used = 3;
   */
  attemptsUsed: number;
};

/**
 * Describes the message dleague.v1.WordleResult.
 * Use `create(WordleResultSchema)` to create a new message.
 */
export const WordleResultSchema: GenMessage<WordleResult> = /*@__PURE__*/
  messageDesc(file_dleague_v1_wordle, 3);

/**
 * Color represents the result of a single letter in a Wordle guess.
 *
 * @generated from enum dleague.v1.Color
 */
export enum Color {
  /**
   * @generated from enum value: COLOR_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * letter not in solution
   *
   * @generated from enum value: COLOR_GRAY = 1;
   */
  GRAY = 1,

  /**
   * letter in solution but wrong position
   *
   * @generated from enum value: COLOR_YELLOW = 2;
   */
  YELLOW = 2,

  /**
   * letter in correct position
   *
   * @generated from enum value: COLOR_GREEN = 3;
   */
  GREEN = 3,
}

/**
 * Describes the enum dleague.v1.Color.
 */
export const ColorSchema: GenEnum<Color> = /*@__PURE__*/
  enumDesc(file_dleague_v1_wordle, 0);

