// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dleague/v1/envelope.proto

package dleaguev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType identifies the payload variant inside Envelope.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_PING        MessageType = 1
	MessageType_MESSAGE_TYPE_PONG        MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_PING",
		2: "MESSAGE_TYPE_PONG",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_PING":        1,
		"MESSAGE_TYPE_PONG":        2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_dleague_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_dleague_v1_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope is the wire frame for every WebSocket message.
// Payload bytes are the marshaled bytes of the inner message identified by `type`.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=dleague.v1.MessageType" json:"type,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUnixMs  int64                  `protobuf:"varint,1,opt,name=client_unix_ms,json=clientUnixMs,proto3" json:"client_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetClientUnixMs() int64 {
	if x != nil {
		return x.ClientUnixMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUnixMs  int64                  `protobuf:"varint,1,opt,name=client_unix_ms,json=clientUnixMs,proto3" json:"client_unix_ms,omitempty"`
	ServerUnixMs  int64                  `protobuf:"varint,2,opt,name=server_unix_ms,json=serverUnixMs,proto3" json:"server_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetClientUnixMs() int64 {
	if x != nil {
		return x.ClientUnixMs
	}
	return 0
}

func (x *Pong) GetServerUnixMs() int64 {
	if x != nil {
		return x.ServerUnixMs
	}
	return 0
}

var File_dleague_v1_envelope_proto protoreflect.FileDescriptor

const file_dleague_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x19dleague/v1/envelope.proto\x12\n" +
	"dleague.v1\"p\n" +
	"\bEnvelope\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.dleague.v1.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\",\n" +
	"\x04Ping\x12$\n" +
	"\x0eclient_unix_ms\x18\x01 \x01(\x03R\fclientUnixMs\"R\n" +
	"\x04Pong\x12$\n" +
	"\x0eclient_unix_ms\x18\x01 \x01(\x03R\fclientUnixMs\x12$\n" +
	"\x0eserver_unix_ms\x18\x02 \x01(\x03R\fserverUnixMs*Y\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_PING\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_PONG\x10\x02B<Z:github.com/tiennm99/dleague/shared/pb/dleague/v1;dleaguev1b\x06proto3"

var (
	file_dleague_v1_envelope_proto_rawDescOnce sync.Once
	file_dleague_v1_envelope_proto_rawDescData []byte
)

func file_dleague_v1_envelope_proto_rawDescGZIP() []byte {
	file_dleague_v1_envelope_proto_rawDescOnce.Do(func() {
		file_dleague_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dleague_v1_envelope_proto_rawDesc), len(file_dleague_v1_envelope_proto_rawDesc)))
	})
	return file_dleague_v1_envelope_proto_rawDescData
}

var file_dleague_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dleague_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dleague_v1_envelope_proto_goTypes = []any{
	(MessageType)(0), // 0: dleague.v1.MessageType
	(*Envelope)(nil), // 1: dleague.v1.Envelope
	(*Ping)(nil),     // 2: dleague.v1.Ping
	(*Pong)(nil),     // 3: dleague.v1.Pong
}
var file_dleague_v1_envelope_proto_depIdxs = []int32{
	0, // 0: dleague.v1.Envelope.type:type_name -> dleague.v1.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dleague_v1_envelope_proto_init() }
func file_dleague_v1_envelope_proto_init() {
	if File_dleague_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dleague_v1_envelope_proto_rawDesc), len(file_dleague_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dleague_v1_envelope_proto_goTypes,
		DependencyIndexes: file_dleague_v1_envelope_proto_depIdxs,
		EnumInfos:         file_dleague_v1_envelope_proto_enumTypes,
		MessageInfos:      file_dleague_v1_envelope_proto_msgTypes,
	}.Build()
	File_dleague_v1_envelope_proto = out.File
	file_dleague_v1_envelope_proto_goTypes = nil
	file_dleague_v1_envelope_proto_depIdxs = nil
}
