// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dleague/v1/envelope.proto

package dleaguev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType identifies the payload variant inside Envelope.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED      MessageType = 0
	MessageType_MESSAGE_TYPE_PING             MessageType = 1
	MessageType_MESSAGE_TYPE_PONG             MessageType = 2
	MessageType_MESSAGE_TYPE_ERROR            MessageType = 3
	MessageType_MESSAGE_TYPE_AUTH_REFRESH     MessageType = 4
	MessageType_MESSAGE_TYPE_AUTH_REFRESH_ACK MessageType = 5
	// Wordle-specific. Future games will introduce their own MESSAGE_TYPE_<GAME>_MOVE/STATE values.
	MessageType_MESSAGE_TYPE_WORDLE_MOVE  MessageType = 6
	MessageType_MESSAGE_TYPE_WORDLE_STATE MessageType = 7
	// Phase 08: async PvP + leaderboard (8–15; 0–7 already used above).
	MessageType_MESSAGE_TYPE_CHALLENGE_CREATE     MessageType = 8
	MessageType_MESSAGE_TYPE_CHALLENGE_CREATE_ACK MessageType = 9
	MessageType_MESSAGE_TYPE_CHALLENGE_JOIN       MessageType = 10
	MessageType_MESSAGE_TYPE_CHALLENGE_JOIN_ACK   MessageType = 11
	MessageType_MESSAGE_TYPE_ATTEMPT_SUBMIT       MessageType = 12
	MessageType_MESSAGE_TYPE_ATTEMPT_SUBMIT_ACK   MessageType = 13
	MessageType_MESSAGE_TYPE_LEADERBOARD_QUERY    MessageType = 14
	MessageType_MESSAGE_TYPE_LEADERBOARD_SNAPSHOT MessageType = 15
	// Phase 09: sync PvP (16–23; 8–15 used by Phase 08 above).
	MessageType_MESSAGE_TYPE_QUEUE_JOIN              MessageType = 16
	MessageType_MESSAGE_TYPE_QUEUE_LEAVE             MessageType = 17
	MessageType_MESSAGE_TYPE_QUEUE_MATCHED           MessageType = 18
	MessageType_MESSAGE_TYPE_MATCH_MOVE              MessageType = 19
	MessageType_MESSAGE_TYPE_MATCH_OPPONENT_PROGRESS MessageType = 20
	MessageType_MESSAGE_TYPE_MATCH_RESOLVED          MessageType = 21
	MessageType_MESSAGE_TYPE_MATCH_REJOIN            MessageType = 22
	MessageType_MESSAGE_TYPE_MATCH_REJOIN_ACK        MessageType = 23
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_PING",
		2:  "MESSAGE_TYPE_PONG",
		3:  "MESSAGE_TYPE_ERROR",
		4:  "MESSAGE_TYPE_AUTH_REFRESH",
		5:  "MESSAGE_TYPE_AUTH_REFRESH_ACK",
		6:  "MESSAGE_TYPE_WORDLE_MOVE",
		7:  "MESSAGE_TYPE_WORDLE_STATE",
		8:  "MESSAGE_TYPE_CHALLENGE_CREATE",
		9:  "MESSAGE_TYPE_CHALLENGE_CREATE_ACK",
		10: "MESSAGE_TYPE_CHALLENGE_JOIN",
		11: "MESSAGE_TYPE_CHALLENGE_JOIN_ACK",
		12: "MESSAGE_TYPE_ATTEMPT_SUBMIT",
		13: "MESSAGE_TYPE_ATTEMPT_SUBMIT_ACK",
		14: "MESSAGE_TYPE_LEADERBOARD_QUERY",
		15: "MESSAGE_TYPE_LEADERBOARD_SNAPSHOT",
		16: "MESSAGE_TYPE_QUEUE_JOIN",
		17: "MESSAGE_TYPE_QUEUE_LEAVE",
		18: "MESSAGE_TYPE_QUEUE_MATCHED",
		19: "MESSAGE_TYPE_MATCH_MOVE",
		20: "MESSAGE_TYPE_MATCH_OPPONENT_PROGRESS",
		21: "MESSAGE_TYPE_MATCH_RESOLVED",
		22: "MESSAGE_TYPE_MATCH_REJOIN",
		23: "MESSAGE_TYPE_MATCH_REJOIN_ACK",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":             0,
		"MESSAGE_TYPE_PING":                    1,
		"MESSAGE_TYPE_PONG":                    2,
		"MESSAGE_TYPE_ERROR":                   3,
		"MESSAGE_TYPE_AUTH_REFRESH":            4,
		"MESSAGE_TYPE_AUTH_REFRESH_ACK":        5,
		"MESSAGE_TYPE_WORDLE_MOVE":             6,
		"MESSAGE_TYPE_WORDLE_STATE":            7,
		"MESSAGE_TYPE_CHALLENGE_CREATE":        8,
		"MESSAGE_TYPE_CHALLENGE_CREATE_ACK":    9,
		"MESSAGE_TYPE_CHALLENGE_JOIN":          10,
		"MESSAGE_TYPE_CHALLENGE_JOIN_ACK":      11,
		"MESSAGE_TYPE_ATTEMPT_SUBMIT":          12,
		"MESSAGE_TYPE_ATTEMPT_SUBMIT_ACK":      13,
		"MESSAGE_TYPE_LEADERBOARD_QUERY":       14,
		"MESSAGE_TYPE_LEADERBOARD_SNAPSHOT":    15,
		"MESSAGE_TYPE_QUEUE_JOIN":              16,
		"MESSAGE_TYPE_QUEUE_LEAVE":             17,
		"MESSAGE_TYPE_QUEUE_MATCHED":           18,
		"MESSAGE_TYPE_MATCH_MOVE":              19,
		"MESSAGE_TYPE_MATCH_OPPONENT_PROGRESS": 20,
		"MESSAGE_TYPE_MATCH_RESOLVED":          21,
		"MESSAGE_TYPE_MATCH_REJOIN":            22,
		"MESSAGE_TYPE_MATCH_REJOIN_ACK":        23,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_dleague_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_dleague_v1_envelope_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope is the wire frame for every WebSocket message.
// Payload bytes are the marshaled bytes of the inner message identified by `type`.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=dleague.v1.MessageType" json:"type,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUnixMs  int64                  `protobuf:"varint,1,opt,name=client_unix_ms,json=clientUnixMs,proto3" json:"client_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetClientUnixMs() int64 {
	if x != nil {
		return x.ClientUnixMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUnixMs  int64                  `protobuf:"varint,1,opt,name=client_unix_ms,json=clientUnixMs,proto3" json:"client_unix_ms,omitempty"`
	ServerUnixMs  int64                  `protobuf:"varint,2,opt,name=server_unix_ms,json=serverUnixMs,proto3" json:"server_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetClientUnixMs() int64 {
	if x != nil {
		return x.ClientUnixMs
	}
	return 0
}

func (x *Pong) GetServerUnixMs() int64 {
	if x != nil {
		return x.ServerUnixMs
	}
	return 0
}

// Error carries a structured error response back to the client.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AuthRefresh is sent by the client ~50 min into a connection to rotate the
// Firebase ID token before the current one expires (tokens last 1 hour).
type AuthRefresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefresh) Reset() {
	*x = AuthRefresh{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefresh) ProtoMessage() {}

func (x *AuthRefresh) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefresh.ProtoReflect.Descriptor instead.
func (*AuthRefresh) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRefresh) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

// AuthRefreshAck is the server's confirmation after successfully re-verifying
// the supplied token. expires_at_unix is the new token's expiry as Unix epoch seconds.
type AuthRefreshAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAtUnix int64                  `protobuf:"varint,1,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefreshAck) Reset() {
	*x = AuthRefreshAck{}
	mi := &file_dleague_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefreshAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshAck) ProtoMessage() {}

func (x *AuthRefreshAck) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshAck.ProtoReflect.Descriptor instead.
func (*AuthRefreshAck) Descriptor() ([]byte, []int) {
	return file_dleague_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRefreshAck) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_dleague_v1_envelope_proto protoreflect.FileDescriptor

const file_dleague_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x19dleague/v1/envelope.proto\x12\n" +
	"dleague.v1\"p\n" +
	"\bEnvelope\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.dleague.v1.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\",\n" +
	"\x04Ping\x12$\n" +
	"\x0eclient_unix_ms\x18\x01 \x01(\x03R\fclientUnixMs\"R\n" +
	"\x04Pong\x12$\n" +
	"\x0eclient_unix_ms\x18\x01 \x01(\x03R\fclientUnixMs\x12$\n" +
	"\x0eserver_unix_ms\x18\x02 \x01(\x03R\fserverUnixMs\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\vAuthRefresh\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"8\n" +
	"\x0eAuthRefreshAck\x12&\n" +
	"\x0fexpires_at_unix\x18\x01 \x01(\x03R\rexpiresAtUnix*\x96\x06\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_PING\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_PONG\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\x03\x12\x1d\n" +
	"\x19MESSAGE_TYPE_AUTH_REFRESH\x10\x04\x12!\n" +
	"\x1dMESSAGE_TYPE_AUTH_REFRESH_ACK\x10\x05\x12\x1c\n" +
	"\x18MESSAGE_TYPE_WORDLE_MOVE\x10\x06\x12\x1d\n" +
	"\x19MESSAGE_TYPE_WORDLE_STATE\x10\a\x12!\n" +
	"\x1dMESSAGE_TYPE_CHALLENGE_CREATE\x10\b\x12%\n" +
	"!MESSAGE_TYPE_CHALLENGE_CREATE_ACK\x10\t\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_CHALLENGE_JOIN\x10\n" +
	"\x12#\n" +
	"\x1fMESSAGE_TYPE_CHALLENGE_JOIN_ACK\x10\v\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_ATTEMPT_SUBMIT\x10\f\x12#\n" +
	"\x1fMESSAGE_TYPE_ATTEMPT_SUBMIT_ACK\x10\r\x12\"\n" +
	"\x1eMESSAGE_TYPE_LEADERBOARD_QUERY\x10\x0e\x12%\n" +
	"!MESSAGE_TYPE_LEADERBOARD_SNAPSHOT\x10\x0f\x12\x1b\n" +
	"\x17MESSAGE_TYPE_QUEUE_JOIN\x10\x10\x12\x1c\n" +
	"\x18MESSAGE_TYPE_QUEUE_LEAVE\x10\x11\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_QUEUE_MATCHED\x10\x12\x12\x1b\n" +
	"\x17MESSAGE_TYPE_MATCH_MOVE\x10\x13\x12(\n" +
	"$MESSAGE_TYPE_MATCH_OPPONENT_PROGRESS\x10\x14\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_MATCH_RESOLVED\x10\x15\x12\x1d\n" +
	"\x19MESSAGE_TYPE_MATCH_REJOIN\x10\x16\x12!\n" +
	"\x1dMESSAGE_TYPE_MATCH_REJOIN_ACK\x10\x17B<Z:github.com/tiennm99/dleague/shared/pb/dleague/v1;dleaguev1b\x06proto3"

var (
	file_dleague_v1_envelope_proto_rawDescOnce sync.Once
	file_dleague_v1_envelope_proto_rawDescData []byte
)

func file_dleague_v1_envelope_proto_rawDescGZIP() []byte {
	file_dleague_v1_envelope_proto_rawDescOnce.Do(func() {
		file_dleague_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dleague_v1_envelope_proto_rawDesc), len(file_dleague_v1_envelope_proto_rawDesc)))
	})
	return file_dleague_v1_envelope_proto_rawDescData
}

var file_dleague_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dleague_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dleague_v1_envelope_proto_goTypes = []any{
	(MessageType)(0),       // 0: dleague.v1.MessageType
	(*Envelope)(nil),       // 1: dleague.v1.Envelope
	(*Ping)(nil),           // 2: dleague.v1.Ping
	(*Pong)(nil),           // 3: dleague.v1.Pong
	(*Error)(nil),          // 4: dleague.v1.Error
	(*AuthRefresh)(nil),    // 5: dleague.v1.AuthRefresh
	(*AuthRefreshAck)(nil), // 6: dleague.v1.AuthRefreshAck
}
var file_dleague_v1_envelope_proto_depIdxs = []int32{
	0, // 0: dleague.v1.Envelope.type:type_name -> dleague.v1.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dleague_v1_envelope_proto_init() }
func file_dleague_v1_envelope_proto_init() {
	if File_dleague_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dleague_v1_envelope_proto_rawDesc), len(file_dleague_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dleague_v1_envelope_proto_goTypes,
		DependencyIndexes: file_dleague_v1_envelope_proto_depIdxs,
		EnumInfos:         file_dleague_v1_envelope_proto_enumTypes,
		MessageInfos:      file_dleague_v1_envelope_proto_msgTypes,
	}.Build()
	File_dleague_v1_envelope_proto = out.File
	file_dleague_v1_envelope_proto_goTypes = nil
	file_dleague_v1_envelope_proto_depIdxs = nil
}
