// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dleague/v1/match.proto

package dleaguev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChallengeCreate is sent by a player after finishing a game to create
// a shareable async PvP challenge.
type ChallengeCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	SeedOverride  int64                  `protobuf:"varint,2,opt,name=seed_override,json=seedOverride,proto3" json:"seed_override,omitempty"` // optional; 0 = use today's daily seed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeCreate) Reset() {
	*x = ChallengeCreate{}
	mi := &file_dleague_v1_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeCreate) ProtoMessage() {}

func (x *ChallengeCreate) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeCreate.ProtoReflect.Descriptor instead.
func (*ChallengeCreate) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeCreate) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ChallengeCreate) GetSeedOverride() int64 {
	if x != nil {
		return x.SeedOverride
	}
	return 0
}

// ChallengeCreateAck is the server's response to ChallengeCreate.
type ChallengeCreateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ShareToken    string                 `protobuf:"bytes,2,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	Seed          int64                  `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeCreateAck) Reset() {
	*x = ChallengeCreateAck{}
	mi := &file_dleague_v1_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeCreateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeCreateAck) ProtoMessage() {}

func (x *ChallengeCreateAck) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeCreateAck.ProtoReflect.Descriptor instead.
func (*ChallengeCreateAck) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeCreateAck) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ChallengeCreateAck) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

func (x *ChallengeCreateAck) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

// ChallengeJoin is sent by a challenger when opening a share link.
type ChallengeJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeJoin) Reset() {
	*x = ChallengeJoin{}
	mi := &file_dleague_v1_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeJoin) ProtoMessage() {}

func (x *ChallengeJoin) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeJoin.ProtoReflect.Descriptor instead.
func (*ChallengeJoin) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeJoin) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

// ChallengeJoinAck is the server's response to ChallengeJoin.
// Note: challenger's attempts are intentionally omitted until after the
// challengee submits their own attempt (anti-cheat).
type ChallengeJoinAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Seed          int64                  `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	GameId        string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeJoinAck) Reset() {
	*x = ChallengeJoinAck{}
	mi := &file_dleague_v1_match_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeJoinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeJoinAck) ProtoMessage() {}

func (x *ChallengeJoinAck) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeJoinAck.ProtoReflect.Descriptor instead.
func (*ChallengeJoinAck) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{3}
}

func (x *ChallengeJoinAck) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ChallengeJoinAck) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ChallengeJoinAck) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

// AttemptSubmit records a player's completed game result for a match.
type AttemptSubmit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Guesses       []string               `protobuf:"bytes,2,rep,name=guesses,proto3" json:"guesses,omitempty"`
	TimeMs        int32                  `protobuf:"varint,3,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Won           bool                   `protobuf:"varint,4,opt,name=won,proto3" json:"won,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptSubmit) Reset() {
	*x = AttemptSubmit{}
	mi := &file_dleague_v1_match_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptSubmit) ProtoMessage() {}

func (x *AttemptSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptSubmit.ProtoReflect.Descriptor instead.
func (*AttemptSubmit) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{4}
}

func (x *AttemptSubmit) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *AttemptSubmit) GetGuesses() []string {
	if x != nil {
		return x.Guesses
	}
	return nil
}

func (x *AttemptSubmit) GetTimeMs() int32 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *AttemptSubmit) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

// AttemptSubmitAck is the server's response after recording an attempt.
// status is "pending" if the other player hasn't submitted yet, or "completed"
// if both sides have submitted and a winner has been decided.
type AttemptSubmitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerUid     string                 `protobuf:"bytes,1,opt,name=winner_uid,json=winnerUid,proto3" json:"winner_uid,omitempty"` // empty when status is "pending"
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // "pending" | "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptSubmitAck) Reset() {
	*x = AttemptSubmitAck{}
	mi := &file_dleague_v1_match_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptSubmitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptSubmitAck) ProtoMessage() {}

func (x *AttemptSubmitAck) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptSubmitAck.ProtoReflect.Descriptor instead.
func (*AttemptSubmitAck) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{5}
}

func (x *AttemptSubmitAck) GetWinnerUid() string {
	if x != nil {
		return x.WinnerUid
	}
	return ""
}

func (x *AttemptSubmitAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// LeaderboardQuery requests the current leaderboard snapshot.
type LeaderboardQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // "daily" | "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardQuery) Reset() {
	*x = LeaderboardQuery{}
	mi := &file_dleague_v1_match_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardQuery) ProtoMessage() {}

func (x *LeaderboardQuery) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardQuery.ProtoReflect.Descriptor instead.
func (*LeaderboardQuery) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{6}
}

func (x *LeaderboardQuery) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *LeaderboardQuery) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// LeaderboardEntry is one row in a leaderboard snapshot.
type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Attempts      int32                  `protobuf:"varint,3,opt,name=attempts,proto3" json:"attempts,omitempty"`
	TimeMs        int32                  `protobuf:"varint,4,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_dleague_v1_match_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardEntry) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LeaderboardEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LeaderboardEntry) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *LeaderboardEntry) GetTimeMs() int32 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// LeaderboardSnapshot is the server's response to LeaderboardQuery.
type LeaderboardSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rankings      []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardSnapshot) Reset() {
	*x = LeaderboardSnapshot{}
	mi := &file_dleague_v1_match_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardSnapshot) ProtoMessage() {}

func (x *LeaderboardSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_match_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardSnapshot.ProtoReflect.Descriptor instead.
func (*LeaderboardSnapshot) Descriptor() ([]byte, []int) {
	return file_dleague_v1_match_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderboardSnapshot) GetRankings() []*LeaderboardEntry {
	if x != nil {
		return x.Rankings
	}
	return nil
}

var File_dleague_v1_match_proto protoreflect.FileDescriptor

const file_dleague_v1_match_proto_rawDesc = "" +
	"\n" +
	"\x16dleague/v1/match.proto\x12\n" +
	"dleague.v1\"O\n" +
	"\x0fChallengeCreate\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12#\n" +
	"\rseed_override\x18\x02 \x01(\x03R\fseedOverride\"d\n" +
	"\x12ChallengeCreateAck\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1f\n" +
	"\vshare_token\x18\x02 \x01(\tR\n" +
	"shareToken\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x03R\x04seed\"0\n" +
	"\rChallengeJoin\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\"Z\n" +
	"\x10ChallengeJoinAck\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x03R\x04seed\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\"o\n" +
	"\rAttemptSubmit\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x18\n" +
	"\aguesses\x18\x02 \x03(\tR\aguesses\x12\x17\n" +
	"\atime_ms\x18\x03 \x01(\x05R\x06timeMs\x12\x10\n" +
	"\x03won\x18\x04 \x01(\bR\x03won\"I\n" +
	"\x10AttemptSubmitAck\x12\x1d\n" +
	"\n" +
	"winner_uid\x18\x01 \x01(\tR\twinnerUid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"C\n" +
	"\x10LeaderboardQuery\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\x90\x01\n" +
	"\x10LeaderboardEntry\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\battempts\x18\x03 \x01(\x05R\battempts\x12\x17\n" +
	"\atime_ms\x18\x04 \x01(\x05R\x06timeMs\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\"O\n" +
	"\x13LeaderboardSnapshot\x128\n" +
	"\brankings\x18\x01 \x03(\v2\x1c.dleague.v1.LeaderboardEntryR\brankingsB<Z:github.com/tiennm99/dleague/shared/pb/dleague/v1;dleaguev1b\x06proto3"

var (
	file_dleague_v1_match_proto_rawDescOnce sync.Once
	file_dleague_v1_match_proto_rawDescData []byte
)

func file_dleague_v1_match_proto_rawDescGZIP() []byte {
	file_dleague_v1_match_proto_rawDescOnce.Do(func() {
		file_dleague_v1_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dleague_v1_match_proto_rawDesc), len(file_dleague_v1_match_proto_rawDesc)))
	})
	return file_dleague_v1_match_proto_rawDescData
}

var file_dleague_v1_match_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_dleague_v1_match_proto_goTypes = []any{
	(*ChallengeCreate)(nil),     // 0: dleague.v1.ChallengeCreate
	(*ChallengeCreateAck)(nil),  // 1: dleague.v1.ChallengeCreateAck
	(*ChallengeJoin)(nil),       // 2: dleague.v1.ChallengeJoin
	(*ChallengeJoinAck)(nil),    // 3: dleague.v1.ChallengeJoinAck
	(*AttemptSubmit)(nil),       // 4: dleague.v1.AttemptSubmit
	(*AttemptSubmitAck)(nil),    // 5: dleague.v1.AttemptSubmitAck
	(*LeaderboardQuery)(nil),    // 6: dleague.v1.LeaderboardQuery
	(*LeaderboardEntry)(nil),    // 7: dleague.v1.LeaderboardEntry
	(*LeaderboardSnapshot)(nil), // 8: dleague.v1.LeaderboardSnapshot
}
var file_dleague_v1_match_proto_depIdxs = []int32{
	7, // 0: dleague.v1.LeaderboardSnapshot.rankings:type_name -> dleague.v1.LeaderboardEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dleague_v1_match_proto_init() }
func file_dleague_v1_match_proto_init() {
	if File_dleague_v1_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dleague_v1_match_proto_rawDesc), len(file_dleague_v1_match_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dleague_v1_match_proto_goTypes,
		DependencyIndexes: file_dleague_v1_match_proto_depIdxs,
		MessageInfos:      file_dleague_v1_match_proto_msgTypes,
	}.Build()
	File_dleague_v1_match_proto = out.File
	file_dleague_v1_match_proto_goTypes = nil
	file_dleague_v1_match_proto_depIdxs = nil
}
