// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dleague/v1/wordle.proto

package dleaguev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Color represents the result of a single letter in a Wordle guess.
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_GRAY        Color = 1 // letter not in solution
	Color_COLOR_YELLOW      Color = 2 // letter in solution but wrong position
	Color_COLOR_GREEN       Color = 3 // letter in correct position
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_GRAY",
		2: "COLOR_YELLOW",
		3: "COLOR_GREEN",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_GRAY":        1,
		"COLOR_YELLOW":      2,
		"COLOR_GREEN":       3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_dleague_v1_wordle_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_dleague_v1_wordle_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_dleague_v1_wordle_proto_rawDescGZIP(), []int{0}
}

// WordleHint holds the per-letter color result for one guess.
type WordleHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Colors        []Color                `protobuf:"varint,1,rep,packed,name=colors,proto3,enum=dleague.v1.Color" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordleHint) Reset() {
	*x = WordleHint{}
	mi := &file_dleague_v1_wordle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordleHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordleHint) ProtoMessage() {}

func (x *WordleHint) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_wordle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordleHint.ProtoReflect.Descriptor instead.
func (*WordleHint) Descriptor() ([]byte, []int) {
	return file_dleague_v1_wordle_proto_rawDescGZIP(), []int{0}
}

func (x *WordleHint) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

// WordleMove is sent client→server carrying the player's guess word.
type WordleMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guess         string                 `protobuf:"bytes,1,opt,name=guess,proto3" json:"guess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordleMove) Reset() {
	*x = WordleMove{}
	mi := &file_dleague_v1_wordle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordleMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordleMove) ProtoMessage() {}

func (x *WordleMove) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_wordle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordleMove.ProtoReflect.Descriptor instead.
func (*WordleMove) Descriptor() ([]byte, []int) {
	return file_dleague_v1_wordle_proto_rawDescGZIP(), []int{1}
}

func (x *WordleMove) GetGuess() string {
	if x != nil {
		return x.Guess
	}
	return ""
}

// WordleState is sent server→client after each move.
// solution is only populated when the game is terminal (won or lost).
type WordleState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Guesses           []string               `protobuf:"bytes,1,rep,name=guesses,proto3" json:"guesses,omitempty"`
	Hints             []*WordleHint          `protobuf:"bytes,2,rep,name=hints,proto3" json:"hints,omitempty"`
	AttemptsRemaining int32                  `protobuf:"varint,3,opt,name=attempts_remaining,json=attemptsRemaining,proto3" json:"attempts_remaining,omitempty"`
	Won               bool                   `protobuf:"varint,4,opt,name=won,proto3" json:"won,omitempty"`
	Lost              bool                   `protobuf:"varint,5,opt,name=lost,proto3" json:"lost,omitempty"`
	// solution is intentionally omitted until terminal to prevent cheating.
	Solution      string `protobuf:"bytes,6,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordleState) Reset() {
	*x = WordleState{}
	mi := &file_dleague_v1_wordle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordleState) ProtoMessage() {}

func (x *WordleState) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_wordle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordleState.ProtoReflect.Descriptor instead.
func (*WordleState) Descriptor() ([]byte, []int) {
	return file_dleague_v1_wordle_proto_rawDescGZIP(), []int{2}
}

func (x *WordleState) GetGuesses() []string {
	if x != nil {
		return x.Guesses
	}
	return nil
}

func (x *WordleState) GetHints() []*WordleHint {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *WordleState) GetAttemptsRemaining() int32 {
	if x != nil {
		return x.AttemptsRemaining
	}
	return 0
}

func (x *WordleState) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

func (x *WordleState) GetLost() bool {
	if x != nil {
		return x.Lost
	}
	return false
}

func (x *WordleState) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

// WordleResult summarises a completed game for leaderboard / history.
type WordleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      string                 `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	Won           bool                   `protobuf:"varint,2,opt,name=won,proto3" json:"won,omitempty"`
	AttemptsUsed  int32                  `protobuf:"varint,3,opt,name=attempts_used,json=attemptsUsed,proto3" json:"attempts_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordleResult) Reset() {
	*x = WordleResult{}
	mi := &file_dleague_v1_wordle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordleResult) ProtoMessage() {}

func (x *WordleResult) ProtoReflect() protoreflect.Message {
	mi := &file_dleague_v1_wordle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordleResult.ProtoReflect.Descriptor instead.
func (*WordleResult) Descriptor() ([]byte, []int) {
	return file_dleague_v1_wordle_proto_rawDescGZIP(), []int{3}
}

func (x *WordleResult) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *WordleResult) GetWon() bool {
	if x != nil {
		return x.Won
	}
	return false
}

func (x *WordleResult) GetAttemptsUsed() int32 {
	if x != nil {
		return x.AttemptsUsed
	}
	return 0
}

var File_dleague_v1_wordle_proto protoreflect.FileDescriptor

const file_dleague_v1_wordle_proto_rawDesc = "" +
	"\n" +
	"\x17dleague/v1/wordle.proto\x12\n" +
	"dleague.v1\"7\n" +
	"\n" +
	"WordleHint\x12)\n" +
	"\x06colors\x18\x01 \x03(\x0e2\x11.dleague.v1.ColorR\x06colors\"\"\n" +
	"\n" +
	"WordleMove\x12\x14\n" +
	"\x05guess\x18\x01 \x01(\tR\x05guess\"\xc6\x01\n" +
	"\vWordleState\x12\x18\n" +
	"\aguesses\x18\x01 \x03(\tR\aguesses\x12,\n" +
	"\x05hints\x18\x02 \x03(\v2\x16.dleague.v1.WordleHintR\x05hints\x12-\n" +
	"\x12attempts_remaining\x18\x03 \x01(\x05R\x11attemptsRemaining\x12\x10\n" +
	"\x03won\x18\x04 \x01(\bR\x03won\x12\x12\n" +
	"\x04lost\x18\x05 \x01(\bR\x04lost\x12\x1a\n" +
	"\bsolution\x18\x06 \x01(\tR\bsolution\"a\n" +
	"\fWordleResult\x12\x1a\n" +
	"\bsolution\x18\x01 \x01(\tR\bsolution\x12\x10\n" +
	"\x03won\x18\x02 \x01(\bR\x03won\x12#\n" +
	"\rattempts_used\x18\x03 \x01(\x05R\fattemptsUsed*Q\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"COLOR_GRAY\x10\x01\x12\x10\n" +
	"\fCOLOR_YELLOW\x10\x02\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x03B<Z:github.com/tiennm99/dleague/shared/pb/dleague/v1;dleaguev1b\x06proto3"

var (
	file_dleague_v1_wordle_proto_rawDescOnce sync.Once
	file_dleague_v1_wordle_proto_rawDescData []byte
)

func file_dleague_v1_wordle_proto_rawDescGZIP() []byte {
	file_dleague_v1_wordle_proto_rawDescOnce.Do(func() {
		file_dleague_v1_wordle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dleague_v1_wordle_proto_rawDesc), len(file_dleague_v1_wordle_proto_rawDesc)))
	})
	return file_dleague_v1_wordle_proto_rawDescData
}

var file_dleague_v1_wordle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dleague_v1_wordle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dleague_v1_wordle_proto_goTypes = []any{
	(Color)(0),           // 0: dleague.v1.Color
	(*WordleHint)(nil),   // 1: dleague.v1.WordleHint
	(*WordleMove)(nil),   // 2: dleague.v1.WordleMove
	(*WordleState)(nil),  // 3: dleague.v1.WordleState
	(*WordleResult)(nil), // 4: dleague.v1.WordleResult
}
var file_dleague_v1_wordle_proto_depIdxs = []int32{
	0, // 0: dleague.v1.WordleHint.colors:type_name -> dleague.v1.Color
	1, // 1: dleague.v1.WordleState.hints:type_name -> dleague.v1.WordleHint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dleague_v1_wordle_proto_init() }
func file_dleague_v1_wordle_proto_init() {
	if File_dleague_v1_wordle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dleague_v1_wordle_proto_rawDesc), len(file_dleague_v1_wordle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dleague_v1_wordle_proto_goTypes,
		DependencyIndexes: file_dleague_v1_wordle_proto_depIdxs,
		EnumInfos:         file_dleague_v1_wordle_proto_enumTypes,
		MessageInfos:      file_dleague_v1_wordle_proto_msgTypes,
	}.Build()
	File_dleague_v1_wordle_proto = out.File
	file_dleague_v1_wordle_proto_goTypes = nil
	file_dleague_v1_wordle_proto_depIdxs = nil
}
